# .github/workflows/deploy.yml

name: Deploy to DigitalOcean Droplet

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Configure Terraform
        run: terraform init

      - name: Deploy to DigitalOcean Droplet
        env:
          DIGITALOCEAN_TOKEN: ${{ secrets.DO_ACCESS_TOKEN }}
        run: terraform apply -auto-approve

